### ISSUE TITLE
Le peuple exige de voir ton site en live !

### ISSUE THREAD

**Issue by kigiri** [brandonsueur/brandonsueur.fr#7]
![image](https://user-images.githubusercontent.com/231748/80867959-9a021700-8c97-11ea-8621-e5a5bdc43974.png)

Merci de passez sur le stream c'est cool, content de te voir evoluer bonne continuation et tout et tout !

**Comment by brandonsueur** [comment]
Héhé, effectivement, j'ai cassé mon VPS, je dois faire ça au plus vite

**Comment by brandonsueur** [comment]
C'est fixé ! ✅🔥
